package com.dtalks.dtalks.user.enums;

public enum ActivityType {
    POST,
    COMMENT,
    QUESTION,
    ANSWER, SELECT_ANSWER, ANSWER_SELECTED,
    STUDY_CREATE, STUDY_JOIN_REQUEST, STUDY_ACCEPTED, STUDY_REQUEST_DENIED, QUIT_STUDY, EXPELLED_STUDY
}
