package com.dtalks.dtalks.notification.enums;

public enum NotificationType {
    COMMENT, RECOMMENT,
    RECOMMEND_POST, RECOMMEND_QUESTION,
    ANSWER, ANSWER_SELECTED,
    STUDY_JOIN_REQUEST, STUDY_MEMBER_AUTO_JOIN, STUDY_MEMBER_QUIT, STUDY_LEVEL_UPDATE,
    STUDY_REQUEST_ACCEPTED, STUDY_REQUEST_DENIED, STUDY_EXPELLED,
    MESSAGE,
    REPORTED, REPORT_RESULT, REPORTED_RESULT
}
