package com.dtalks.dtalks.alarm.enums;

public enum AlarmType {
    COMMENT, RECOMMENT,
    RECOMMEND_POST, RECOMMEND_QUESTION,
    ANSWER, ANSWER_SELECTED,
    STUDY_JOIN_REQUEST, STUDY_REQUEST_ACCEPTED, STUDY_REQUEST_DENIED, STUDY_MEMBER_QUIT, STUDY_EXPELLED, STUDY_LEVEL_UPDATE
}
